root: true
env:
  es6: false
  browser: true
  node: true
  jest: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - eslint-config-prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  sourceType: module
globals:
  NodeJS: true
plugins:
  - "@typescript-eslint"
rules:
  no-undef:
    - error
  quotes:
    - warn
    - single
  no-constant-condition:
    - warn
  prefer-const:
    - warn
  "@typescript-eslint/ban-types":
    - off
  "@typescript-eslint/no-var-requires":
    - warn
  "@typescript-eslint/no-inferrable-types":
    - off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_$"
  "@typescript-eslint/no-non-null-assertion":
    - off
  "@typescript-eslint/no-unnecessary-type-constraint":
    - off
  "@typescript-eslint/no-explicit-any":
    - off
settings:
  react:
    version: "detect"